{
 "title": "stick tables",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "table",
    "label": "table",
    "query": "label_values(trt3_haproxy_sticktable_curr_entries, table)"
   },
   { "name": "interval", "label": "rate interval", "query": "10s,30s,1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IPs na tabela",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trt3_haproxy_sticktable_curr_entries{table=\"$table\"}",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "FE Requests Denied",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_requests_denied_total[1m])",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "FE Connections Denied",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_denied_connections_total[1m])",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Quantis Tcp ConnRate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(trt3_haproxy_sticktable_tcp_conn_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(trt3_haproxy_sticktable_tcp_conn_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(trt3_haproxy_sticktable_tcp_conn_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.50, rate(trt3_haproxy_sticktable_tcp_conn_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.50"
    }
   ]
  },
  {
   "title": "Amostras nos últimos 60s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(trt3_haproxy_sticktable_tcp_conn_rate_count{table=\"$table\"}[1m])",
     "legendFormat": "Amostras"
    }
   ]
  },
  {
   "title": "Média dos últimos 60s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(trt3_haproxy_sticktable_tcp_conn_rate_sum{table=\"$table\"}[1m]) / delta(trt3_haproxy_sticktable_tcp_conn_rate_count{table=\"$table\"}[1m])",
     "legendFormat": "conn/1s"
    }
   ]
  },
  {
   "title": "conn_rate rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(trt3_haproxy_sticktable_tcp_conn_rate_bucket{table=\"$table\"}[$interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Quantis Http ReqRate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(trt3_haproxy_sticktable_http_req_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(trt3_haproxy_sticktable_http_req_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(trt3_haproxy_sticktable_http_req_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.50, rate(trt3_haproxy_sticktable_http_req_rate_bucket{table=\"$table\"}[1m]))",
     "legendFormat": "0.50"
    }
   ]
  },
  {
   "title": "Amostras nos últimos 60s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(trt3_haproxy_sticktable_http_req_rate_count{table=\"$table\"}[1m])",
     "legendFormat": "Amostras"
    }
   ]
  },
  {
   "title": "Média dos últimos 60s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(trt3_haproxy_sticktable_http_req_rate_sum{table=\"$table\"}[1m]) / delta(trt3_haproxy_sticktable_http_req_rate_count{table=\"$table\"}[1m])",
     "legendFormat": "reqs/1s"
    }
   ]
  },
  {
   "title": "http_req rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(trt3_haproxy_sticktable_http_req_rate_bucket{table=\"$table\"}[$interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}