version: '3'
services:
  exporter:
    build:
      context: ../..
    image: smveloso/haproxy-stick-tables-exporter:latest
    volumes:
      - ./haproxy/socket:/var/haproxy
    ports:
      - "9752:9752"
    command: 
      - "-namespace"
      - "acme"
      #- "-subsystem"
      #- "haproxyx"
  httpd:
    ports:
      - "8081:80"
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf
      - ./httpd/data/default:/usr/local/apache2/htdocs/default
    image: "httpd:2.4.41-alpine"
  haproxy:
    ports:
      - "8080:80"
      - "8443:443"
      - "1936:1936"
      - "10253:10253"
    volumes:
      - ./haproxy/conf:/usr/local/etc/haproxy
      - ./haproxy/socket:/var/haproxy
    image: "haproxy:2.0.5-alpine"
  syslog:
    volumes:
      - ./haproxy/logs:/var/log
    image: "balabit/syslog-ng:latest"
  prometheus:
    user: "1000"
    image: "prom/prometheus:v2.21.0"
    command: 
      - "--web.enable-admin-api"
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
  grafana:
    user: "1000"
    image: "grafana/grafana:7.1.5"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
  stress:
    build:
      context: ./stress
    image: smveloso/stress:latest
    cap_add:
      - NET_ADMIN
